[build]
builder = "NIXPACKS"

[variables]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "maneira-crm-backend"
