[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node dist/main.js"
healthcheckPath = "/api/dashboard"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "maneira-crm-backend"
